# Generated by Django 3.2.2 on 2021-05-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('Phone', models.IntegerField()),
                ('Date', models.DateField(auto_now=True)),
                ('Buy_kgs', models.IntegerField()),
                ('extra_kgs', models.IntegerField()),
                ('Rate', models.IntegerField()),
                ('Bill', models.IntegerField()),
            ],
        ),
    ]
