# Generated by Django 3.2.2 on 2021-05-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcustomer',
            name='Bill',
            field=models.IntegerField(null=True),
        ),
    ]
