# Generated by Django 3.2.2 on 2021-05-16 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_details', '0002_alter_addcustomer_bill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addcustomer',
            options={'ordering': ['-Date']},
        ),
        migrations.AddField(
            model_name='addcustomer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='addcustomer',
            name='Buy_kgs',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='addcustomer',
            name='extra_kgs',
            field=models.FloatField(),
        ),
    ]
