# Generated by Django 3.2.2 on 2021-05-16 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_details', '0003_auto_20210516_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addcustomer',
            options={},
        ),
        migrations.AlterOrderWithRespectTo(
            name='addcustomer',
            order_with_respect_to='user',
        ),
    ]
