# Generated by Django 4.0.4 on 2022-05-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_details', '0004_auto_20210516_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('contact_number', models.IntegerField()),
                ('message', models.CharField(max_length=2000)),
            ],
        ),
    ]
