# Generated by Django 4.0.4 on 2022-05-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_details', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcustomer',
            name='Pending',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
